name: Build

on:
  pull_request:
    branches: 
      - silje-clock
  push:
    branches:
      - silje-clock

env:
  COLOR: BLUE

jobs: 
  build:
    container:
      image: ghcr.io/armmbed/mbed-os-env:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Compile movement firmware
        run: make
        working-directory: '.'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: movement.uf2
          path: build/firmware.uf2

  build-simulator:
    container:
      image: emscripten/emsdk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Compile movement
        run: emmake make
        working-directory: '.'
      - name: Archive simulator build
        working-directory: './build-sim'
        run: |
          cp firmware.html index.html
          tar -czf movement.tar.gz firmware.html firmware.wasm firmware.js
      - name: Upload simulator build
        uses: actions/upload-artifact@v4
        with:
          name: movement.tar.gz
          path: build-sim/movement.tar.gz
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './build-sim'
          production-branch: eirik-clock
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_SC }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_SC }}
        timeout-minutes: 1
